# Generated by Django 4.1.7 on 2023-04-20 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='input_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=14, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)])),
                ('purchase_date', models.DateField()),
                ('serial_no', models.IntegerField()),
                ('bill_no', models.IntegerField()),
                ('economic_code', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('name_of_item', models.CharField(max_length=255)),
                ('costs_of_asset_sold', models.DecimalField(decimal_places=10, max_digits=20)),
                ('current_balance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('asset_code_generated', models.CharField(max_length=14, validators=[django.core.validators.MaxLengthValidator(14), django.core.validators.MinLengthValidator(14)])),
                ('asset_code', models.CharField(max_length=14, validators=[django.core.validators.MaxLengthValidator(14), django.core.validators.MinLengthValidator(14)])),
                ('expected_life', models.IntegerField()),
                ('depriciation_method', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('current_depreciation', models.DecimalField(decimal_places=10, max_digits=20)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=10, max_digits=20)),
                ('current_condition', models.CharField(max_length=255)),
            ],
        ),
    ]
