# Generated by Django 4.1.7 on 2023-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afar_app', '0005_alter_input_field_asset_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_field',
            name='financial_year',
            field=models.CharField(max_length=250),
        ),
    ]
