# Generated by Django 4.2.6 on 2023-11-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afar_app', '0013_depriciation_field_deprication_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_field',
            name='asset_code',
        ),
        migrations.RemoveField(
            model_name='input_field',
            name='deprication_rate',
        ),
        migrations.RemoveField(
            model_name='input_field',
            name='economic_code',
        ),
        migrations.RemoveField(
            model_name='input_field',
            name='expected_life',
        ),
        migrations.RemoveField(
            model_name='input_field',
            name='financial_year',
        ),
    ]
