# Generated by Django 4.2.6 on 2023-12-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afar_app', '0016_model_asset_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depriciation_field',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='input_field',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model_asset_info',
            name='economic_code',
            field=models.CharField(max_length=100),
        ),
    ]
