# Generated by Django 4.2.9 on 2024-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afar_app', '0017_alter_depriciation_field_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_field',
            name='sold_quantity',
        ),
        migrations.AddField(
            model_name='input_field',
            name='Salvage_Value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
