# Generated by Django 4.2.6 on 2024-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='impairmententry_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value_in_use', models.FloatField()),
                ('Fair_value_less_cost_to_sale', models.FloatField()),
            ],
        ),
    ]
