# Generated by Django 4.2.6 on 2024-02-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairmenttest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impairmententry_model',
            name='Fair_value_less_cost_to_sale',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='impairmententry_model',
            name='Value_in_use',
            field=models.FloatField(null=True),
        ),
    ]
