# Generated by Django 4.2.9 on 2024-02-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairmenttest', '0002_alter_impairmententry_model_fair_value_less_cost_to_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='entryfinderm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_Code', models.CharField(max_length=128)),
            ],
        ),
    ]
