# Generated by Django 4.2.9 on 2024-02-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairmenttest', '0003_entryfinderm'),
    ]

    operations = [
        migrations.AddField(
            model_name='impairmententry_model',
            name='Asset_Code',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entryfinderm',
            name='Asset_Code',
            field=models.CharField(),
        ),
    ]
