# Generated by Django 4.2.7 on 2024-02-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairmenttest', '0004_impairmententry_model_asset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impairmententry_model',
            name='Financial_year',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
